name: Gitleaks PR Secret Scan

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  gitleaks:
    uses: clouddrove/github-shared-workflows/.github/workflows/gitleaks-pr-scan.yml@0d9fa74b29d820d7ffe031704ec53bf7653c97c3 # pinned to latest
    secrets: inherit
