name: Gitleaks PR Secret Scan

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  gitleaks:
    uses: clouddrove/github-shared-workflows/.github/workflows/gitleaks-pr-scan.yml@21cd5a8d11a5f01560103ac3fcae05835e9e3699 # pinned to latest
    secrets: inherit
