name: Module Test Harness

on:
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  basic-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/stf-checks.yml@21cd5a8d11a5f01560103ac3fcae05835e9e3699
    with:
      provider: digitalocean
      working_directory: ./_examples/basic/

  complete-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/stf-checks.yml@21cd5a8d11a5f01560103ac3fcae05835e9e3699
    with:
      provider: digitalocean
      working_directory: ./_examples/complete/

  soc2-baseline-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/stf-checks.yml@21cd5a8d11a5f01560103ac3fcae05835e9e3699
    with:
      provider: digitalocean
      working_directory: ./_examples/soc2-baseline/
