name: Module Test Harness

on:
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  basic-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/stf-checks.yml@0d9fa74b29d820d7ffe031704ec53bf7653c97c3
    with:
      provider: digitalocean
      working_directory: ./_examples/basic/

  complete-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/stf-checks.yml@0d9fa74b29d820d7ffe031704ec53bf7653c97c3
    with:
      provider: digitalocean
      working_directory: ./_examples/complete/

  soc2-baseline-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/stf-checks.yml@0d9fa74b29d820d7ffe031704ec53bf7653c97c3
    with:
      provider: digitalocean
      working_directory: ./_examples/soc2-baseline/
